### ISSUE TITLE
[contact] How to compile this project?

### ISSUE THREAD

**Issue by bphucc** [25077667/VMPilot#2]
Hello, I tried compile using cMake on Windows and Ubuntu, but it gives bunch of errors, in Windows it said that I've not configured OpenSSL, but I added it already to my system environment variables, on Linux the autoconf messed up..

So, do you have any more detailed to compile this tool, I would very much appreciate. Thanks in advance!!

**Comment by 25077667** [comment]
Hello,

TL;DR: Could you assist me in testing the dev branch?

===
I have been working on linking OpenSSL statically, but I have encountered difficulties in doing so. As a result, I have decided to remove the OpenSSL dependency by migrating it to [Botan](https://github.com/randombit/botan).

Your assistance in testing the dev branch would be greatly appreciated.

Please let me know if you have any questions or need further clarification.

Thank you.

**Comment by bphucc** [comment]
Yes, I do want to help you on tesing dev branch. How should we contact btw? This project looks awesome 🙂

**Comment by 25077667** [comment]
You could contact me at: [zxc25077667\[at\]gmail.com](zxc25077667@gmail.com).

**Comment by 25077667** [comment]
@bphucc BTW, could you help me try this commit?
https://github.com/25077667/VMPilot/commit/6f183147ceb0f76b9064751ab798ce81e071da20

**Comment by bphucc** [comment]
I configured and compiled without any issue, platform is a fresh Windows 10 21H2, I also installed OpenSSL from [this link](https://slproweb.com/products/Win32OpenSSL.html)(full installer), and set the OPENSSL_INCLUDE_DIR manually in the cMake configuration, this is the result:
![image](https://github.com/25077667/VMPilot/assets/42881433/7c1899aa-cc47-43e2-a55d-981adc1d4549)

You want any other information? Btw I also finding for sdk.hpp file for testing out the obfuscation, but I couldn't find it.

**Comment by 25077667** [comment]
Thank you for your update. It's great to hear that you were able to configure and compile everything smoothly on a fresh Windows 10 21H2 platform.

Regarding the `sdk.hpp` file for testing out the obfuscation, I apologize for any confusion caused. The `sdk.hpp` file is currently a work in progress and not yet available. Once it is ready for testing, we will make sure to provide it to you.

If you have any other questions or need further assistance, please feel free to let me know.
